name: Go

on:
  push:
    branches: [ '*' ]
    paths-ignore: ['/docs', '/README.md']
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: start docker-compose stack
      run:  docker-compose -f kafka.docker-compose.yml up -d

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
